### ISSUE TITLE
Fort Funston Webcam images broken

### ISSUE THREAD

**Issue by RobertMParker** [RobertMParker/mr-weather#4]
The issue is that Chrome updated, and it no longer allows mixed content.  The page is HTTPS, but the Fort Funston images are HTTP.  It used to work, but display a warning about mixed content.  Now Chrome tries to load the images via HTTPS, and it fails since Fort Funston's webserver does not have a valid certificate.

So since I can't fix Fort Funston's webserver, I can either downgrade the entire site to HTTP or try to figure out some stupid HTTPS proxy to fool Chrome.

**Comment by RobertMParker** [comment]
I haven't been able to find a free pass through proxy, I have been able to find free image proxy services that have caches.  And a long cache would kind of make this worthless for a webcam picture.

**Comment by tris** [comment]
Oh no.  It still works for me, on Chrome 85.0.4183.121 on OS X... (which is supposedly up to date.)

**Comment by RobertMParker** [comment]
I assume the restriction of mixed content may be in the process of rolling out, so it may not effect everyone else yet.  The change is documented here: https://security.googleblog.com/2019/10/no-more-mixed-messages-about-https_3.html

But this should be fixed with this change:
https://github.com/RobertMParker/mr-weather/commit/31f82b57e87fde53a855d50da3687d3fda73ea6d#diff-eacf331f0ffc35d4b482f1d15a887d3b
