### ISSUE TITLE
Potential stale images from Mussel Rock webcams

### ISSUE THREAD

**Issue by RobertMParker** [RobertMParker/mr-weather#5]
The Mussel Rock webcams are currently showing fog, but the area is clear of fog.  And right now when I go to the page:
https://www.wunderground.com/dashboard/webcam/barenjager/8/2020-9-30

Below the images, it has the text "Online: 1:56:06 PM (updated 3 hours ago)".

So weather underground is showing a stale image, which isn't very useful.  At the very least it should display the staleness of the image.

**Comment by RobertMParker** [comment]
I just refreshed the page while debugging, and now it displays "Online: 5:26:35 PM (updated -9 mins ago)"

The data is from the future!

**Comment by RobertMParker** [comment]
I couldn't find the API call to get how old the image is, and the image doesn't contain any EXIF metadata.  But the HTTP response does contain the following headers. I think that "last-modified" header is the timestamp when the image was taken, and currently it is 5.5 hours old.

Also interesting to note that the image is being served via AWS S3.

accept-ranges: bytes
access-control-allow-credentials: false
access-control-allow-headers: *
access-control-allow-methods: GET,POST
access-control-allow-origin: *
access-control-max-age: 86400
content-length: 23470
content-type: image/jpeg
date: Thu, 01 Oct 2020 00:28:16 GMT
etag: "24bddbe6b2873518c4a540eb7aa4aa70"
expires: Thu, 01 Oct 2020 00:28:16 GMT
last-modified: Wed, 30 Sep 2020 20:45:28 GMT
server: AmazonS3
status: 304
x-amz-expiration: expiry-date="Fri, 02 Oct 2020 00:00:00 GMT", rule-id="Delete Objects After 24 hours"
x-amz-id-2: W1VRp+g7xbXbkPOUkGpfeKFw0iCng3TO+c5DdIcjUNPCanHUk+D92vPbZC4tls0VwBX6aKiAkdc=
x-amz-request-id: E0A1A1E0746B546C

**Comment by RobertMParker** [comment]
Actually I don't think those headers are useful at all.

The other webcam has a last-modified header of:
Thu, 01 Oct 2020 00:43:28 GMT

Current GMT is October 1, 2020 12:48:28 AM

So that would be twelve hours ago, and the image is showing a current scene.  Twelve hours ago would have been still dark outside.  So that value isn't useful for this.

**Comment by RobertMParker** [comment]
This documentation page is currently broken, but it may have some answers:
https://api.wunderground.com/weather/api/d/docs?d=data/webcams

Here is a cached version, which doesn't really explain the query syntax:
https://web.archive.org/web/20190119154426/https://api.wunderground.com/weather/api/d/docs?d=data/webcams

**Comment by RobertMParker** [comment]
So the webcams in question are listed as being in Daly, City.  How many webcams on Weather Underground can there be in Daly CIty?  So I thought I could take the API key that I've been using, and just query the status of all the nearby webcams using this URL: http://api.wunderground.com/api/6532d6454b8aa370768e63d6ba5a832e/webcams/q/CA/Daly_City.json

But no dice.  Got a 503 error code.  Maybe this is temporary...

**Comment by RobertMParker** [comment]
Ahh maybe that API key isn't going to work.  I forgot that I found the API key by dissecting the weatherunderground website, but it is actually used to access apis for api.weather.com

The weatherunderground apis might be dead.

**Comment by tris** [comment]
Yeah, between poor API support from WU and the poor reliability of the cameras, I'm not sure it's worth a lot of effort.  I used to think that the timelapse video was more trustworthy, but if you look at one of [today's](https://icons.wunderground.com/webcamarchive/b/a/barenjager/5/2020/10/2020101.mp4) it goes from light to dark to light to dark to light to dark to ... you get the idea. :(

FWIW, you can get a static image for the Cheetah camera [here](https://i.ytimg.com/vi/L6e1EEA-dQI/maxresdefault.jpg), but it has similar caching issues.  Adding a random query string seems to help.  (Though also might as well just embed the iframe. :)

**Comment by RobertMParker** [comment]
Yep, it's not worth the effort.  I ended up adding a note that the images may be stale.
